### ISSUE TITLE
git_client is not found in v7_0

### ISSUE THREAD

**Issue by lgc019** [microsoft/azure-devops-python-api#453] opened 2023-04-19 11:45 UTC
No module named 'azure.devops.v7_0.git.git_client' when trying to use get_git_client()

**Comment by MarcoPalu97** [comment] 2023-04-19 15:32
Same issue spotted by me:

File "/home/vsts/.local/lib/python3.10/site-packages/azure/devops/released/client_factory.py", line 135, in get_git_client
    return self._connection.get_client('azure.devops.v7_0.git.git_client.GitClient')
  File "/home/vsts/.local/lib/python3.10/site-packages/azure/devops/connection.py", line 44, in get_client
    client_class = self._get_class(client_type)
  File "/home/vsts/.local/lib/python3.10/site-packages/azure/devops/connection.py", line 52, in _get_class
    imported = __import__(module_name)
  File "/home/vsts/.local/lib/python3.10/site-packages/azure/devops/v7_0/git/__init__.py", line 10, in <module>
    from .git_client import GitClient
**ModuleNotFoundError: No module named 'azure.devops.v7_0.git.git_client'**

Seems like you missed to create the module _git_client.py_ into the v7_0 of the git client, I found it when comparing with v6_0

**Comment by jknoy** [comment] 2023-04-19 15:34
Seeing the same problem. Looks like git_client.py was deleted as part of v5.1 cleanup, but now missing and causing errors.

**Comment by detmoo** [comment] 2023-04-19 15:54
Also have problem with this. Looks like `from .git_client import GitClient` is no longer valid import. Initial look seems like GitClient might have become GitClientBase in v7?

Will be standing by for rapid roll-out of the necessary fix please.

**Comment by yishuiliunian** [comment] 2023-04-22 05:06
I have created a PR to fix it. But it is waiting for approval. 

https://github.com/microsoft/azure-devops-python-api/pull/456

**Comment by nechvatalp** [comment] 2023-04-25 07:09
Thanks for reporting, investigating

**Comment by nechvatalp** [comment] 2023-04-25 19:15
This should be fixed in 7.1.0b2, the source we generate from is setup to generate git_client_base, previous maintainer created the git_client manually as it is more intuitive I wasn't aware of that so didn't include this file.

Added it back in.

**Comment by brbeec** [comment] 2023-04-25 23:58
@nechvatalp I'm no longer seeing ModuleNotFoundError when calling get_git_client() after #457, however, I'm now seeing DeserializationError when calling get_commits().

`azure.core.exceptions.DeserializationError: ("Unable to deserialize to object: type, KeyError: 'ChangeCountDictionary'", KeyError('ChangeCountDictionary'))`

It doesn't look like ChangeCountDictionary is defined in models.py?

**Comment by nechvatalp** [comment] 2023-04-26 17:41
Yes, issue was indeed with the ChangeCountDictionary I updated the models, @brbeec could you check if the issue is resolved for you in 7.1.0b3?

**Closed** 2023-04-27 16:17 UTC
Labels: bug
